version: '3.9'

services:
  db:
    image: postgres:15
    container_name: libreria_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: libreria_user
      POSTGRES_PASSWORD: libreria_pass
      POSTGRES_DB: libreria_inventario
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/dblibreria.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U libreria_user -d libreria_inventario"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: libreria_backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: libreria_user
      DB_PASSWORD: libreria_pass
      DB_DATABASE: libreria_inventario
      JWT_SECRET: libreria_super_secret_jwt_2024
      JWT_EXPIRES_IN: 8h
      PORT: 3001
      FRONTEND_URL: http://localhost
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: libreria_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  db_data:
