databases:
  - name: libreria-db
    databaseName: libreria_inventario
    plan: free
    region: ohio
    user: libreria_user
    ipAllowList: []

services:
  - type: web
    name: libreria-backend
    runtime: node
    repo: https://github.com/cdqh777/proy_backend_pagina.git
    plan: free
    region: ohio
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run db:init && npm run start:prod
    healthCheckPath: /api/categories
    envVars:
      - key: DB_HOST
        value: dpg-d8pvnadckfvc73f0jm60-a
      - key: DB_PORT
        value: 5432
      - key: DB_USERNAME
        value: postgrest
      - key: DB_PASSWORD
        value: WAOQHHuQkOTrikcwSu0lAyUgzvaZcE3i
      - key: DB_DATABASE
        value: proy_libinv
      - key: JWT_SECRET
        value: libreria_super_secret_key_2024
      - key: JWT_EXPIRES_IN
        value: 8h
      - key: PORT
        value: 3001
      - key: FRONTEND_URL
        value: https://libreria-frontend.onrender.com

  - type: static
    name: libreria-frontend
    rootDir: frontend
    buildCommand: npm install --legacy-peer-deps && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: libreria-backend
          type: web
          property: url
